#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : conky
Version  : 1.11.5
Release  : 4
URL      : https://github.com/brndnmtthws/conky/archive/v1.11.5.tar.gz
Source0  : https://github.com/brndnmtthws/conky/archive/v1.11.5.tar.gz
Summary  : Lightweight system monitor for X
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0 MIT
Requires: conky-bin = %{version}-%{release}
Requires: conky-data = %{version}-%{release}
Requires: conky-lib = %{version}-%{release}
Requires: conky-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-scons
BuildRequires : glibc-dev
BuildRequires : imlib2-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : lua-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-xlib)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libmicrohttpd)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(librsvg-2.0)

%description
DA DOCS. YO.
============
The main file that contains the bulk of our documentation is docs.xml .
We use the DocBook format, which is a really kickass xml-based way of
writing documentation, heavily oriented towards programming and computer
stuff. There are tags like <command> and <option> that marks up your
content without actually having to mark it up, which is why something
that's of the <command> shows up in some cool style regardless of
whether it's in a man page or a web page. DocBook has been around for
10 years, and there's TONS of resources online about the different
tags and the stuff that can be done.

%package bin
Summary: bin components for the conky package.
Group: Binaries
Requires: conky-data = %{version}-%{release}
Requires: conky-license = %{version}-%{release}

%description bin
bin components for the conky package.


%package data
Summary: data components for the conky package.
Group: Data

%description data
data components for the conky package.


%package doc
Summary: doc components for the conky package.
Group: Documentation

%description doc
doc components for the conky package.


%package lib
Summary: lib components for the conky package.
Group: Libraries
Requires: conky-data = %{version}-%{release}
Requires: conky-license = %{version}-%{release}

%description lib
lib components for the conky package.


%package license
Summary: license components for the conky package.
Group: Default

%description license
license components for the conky package.


%prep
%setup -q -n conky-1.11.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1566315750
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DBUILD_PORT_MONITORS=OFF -DBUILD_LUA_CAIRO=ON
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1566315750
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/conky
cp 3rdparty/toluapp/COPYRIGHT %{buildroot}/usr/share/package-licenses/conky/3rdparty_toluapp_COPYRIGHT
cp LICENSE %{buildroot}/usr/share/package-licenses/conky/LICENSE
cp LICENSE.BSD %{buildroot}/usr/share/package-licenses/conky/LICENSE.BSD
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/conky

%files data
%defattr(-,root,root,-)
/usr/share/applications/conky.desktop
/usr/share/icons/hicolor/scalable/apps/conky-logomark-violet.svg

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/conky-1.11.5_pre/conky.conf
/usr/share/doc/conky-1.11.5_pre/conky_no_x11.conf
/usr/share/doc/conky-1.11.5_pre/convert.lua

%files lib
%defattr(-,root,root,-)
/usr/lib64/conky/libcairo.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/conky/3rdparty_toluapp_COPYRIGHT
/usr/share/package-licenses/conky/LICENSE
/usr/share/package-licenses/conky/LICENSE.BSD
